### ISSUE TITLE
travis: html-proofer needs ruby 2.2 or newer

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/mlr-org.github.io#10]
@jakobbossek can you have a look at this?

https://travis-ci.org/mlr-org/mlr-org.github.io/builds/168625938

**Comment by jakobbossek** [comment]
Sure. I can have a look at it at the end of the next week.
Really busy at the moment with teaching.

**Comment by jakob-r** [comment]
I think I was able to fix it. Wasn't so complicated.

**Comment by jakobbossek** [comment]
Ok 👍  Great.
