### ISSUE TITLE
Contributors link broken on mlr-org.github.io/about

### ISSUE THREAD

**Issue by heoa** [mlr-org/mlr-org.github.io#14]
The About page (1) leads to (2) that is broken.

(1) http://mlr-org.github.io/about/
(2) https://github.com/mlr-org/mlr/wiki/mlr-developer-team-and-contributors-page

**Comment by berndbischl** [comment]
sorry, where exactly is a broken link?

**Comment by heoa** [comment]
It was from page http://mlr-org.github.io/about/ to this page https://github.com/mlr-org/mlr/wiki/mlr-developer-team-and-contributors-page causing an error not available but now it is available, odd, perhaps some github hosting problem?

**Comment by berndbischl** [comment]
ok, dunno.
thx.
